### ISSUE TITLE
Login can a long take time and cause QGIS to become unresponsive whilst loading

### ISSUE THREAD

**Issue by SDScandrettKint** [archesproject/arches-qgis#3]
Entering url and login can take some time, and the UI looks like it has crashed, especially if the user clicks on the dialog it'll show "Not responding".  

Video demonstration:

https://github.com/archesproject/arches-qgis/assets/119508494/60711801-97c3-488c-92ca-74749aa6a366

NOTE: before I changed my local environment I used Arches-via-docker, and this was much faster to log in, and this issue did not occur.  Now I have reverted back to using a standard Arches local deployment (non-containerised) and this issue has surfaced.  This could be a red herring and unrelated though.

**Comment by samuelscandrett** [comment]
From a related stackoverflow thread - https://gis.stackexchange.com/questions/416403/qgis-crashes-when-creating-many-features-through-plugin

> To keep your GUI responsive you need to use background threads. You can use [QgsTask](https://qgis.org/pyqgis/3.16/core/QgsTask.html) for this or also [QThread](https://doc.qt.io/qtforpython/PySide6/QtCore/QThread.html) or other methods to do this. Note that communicating from a background thread with the GUI directly will cause an immediate crash! So never ever use print() in a background thread!

Should we be using task manager or queues to make API calls?  Then include loading symbol to show the plugin is working in the background.
